config {
  tags: ["hourly"],
  type: "table",
  schema: "dataform_granular",
  bigquery: {
    partitionBy: "event_date"
  }
}

pre_operations {

  declare max_date default (
  
    SELECT CAST(FORMAT_DATE('%Y%m%d', MAX(event_date)) AS STRING) FROM ${ref('pageviews')}
  
  );

}

select
  
  parse_date("%Y%m%d", event_date) event_date,
  event_timestamp,
  user_pseudo_id,
  (select value.int_value from unnest(event_params) where key = "ga_session_id") ga_session_id,
  (select value.string_value from unnest(event_params) where key = 'page_location') page_location,
  (select value.string_value from unnest(event_params) where key = "clicked_details_id") clicked_details_id,
  (select value.string_value from unnest(event_params) where key = "clicked_details_classes") clicked_details_classes,
  (select value.string_value from unnest(event_params) where key = "clicked_details_url") clicked_details_url,
  (select value.string_value from unnest(event_params) where key = "clicked_details_tagName") clicked_details_tag_name,
  (select value.string_value from unnest(event_params) where key = "clicked_details_text") clicked_details_text,

from `analytics_316501895.events_*`

where
  event_name = "page_view"
  and _table_suffix > max_date

union all

select * from ${ref("pageviews")} where event_date > date_sub(current_date, interval 90 day)
